### PR TITLE
Convert to UTF-32 instead of UCS-2, since we aren't living in the stone age

### PR DESCRIPTION
**Pull request by endrift**
Seriously, who uses UCS-2? There's no benefit here, only detriment.

### CODE REVIEW

**Comment by TheOfficialFloW** [comment]
Unfortunately your 'not-stone age' broke unicode support. Please change back to UCS-2. PGF does not understand UTF-32 characters.

**Comment by xerpi** [comment]
Maybe we should use UCS-2 for PGF and UTF-32 for freetype2?

**Comment by endrift** [comment]
@TheOfficialFloW please explain how this is possible. You're just passing in ints, which for BMP characters will be exactly the same. Moreover, I've tested this and Japanese characters show up just fine.

**Comment by TheOfficialFloW** [comment]
Hm, sorry my bad, the value should indeed be same, however it isn't the case with your conversion method. I'm not sure where the bug lies, however this is the difference when using VitaShell:

With your conversion:
https://i.imgsafe.org/cb07db4073.jpeg

With mine:
https://i.imgsafe.org/cb07fdc44f.jpeg

**Comment by endrift** [comment]
Hm, strange. Using my version, UTF-8 displays fine in mGBA, or at least katakana does, I'm not sure about other ranges. Perhaps we're using the API differently?

**Comment by endrift** [comment]
I think I've figured out the problem. Did your UCS-2 version fall back to Latin-1 if conversion failed?

E] yep that's exactly what's going on--the UTF-8 conversion in my version doesn't fall back if it can't find a valid UTF-8 sequence, whereas yours does.

**Comment by TheOfficialFloW** [comment]
Ah yeah indeed, totally forgot that I added those checks to make it working finely

**Comment by endrift** [comment]
Perhaps there should be two versions of the function, one which takes in UTF-8 and one which takes in Latin-1, as these "fallback" cases are a kludge at best, and a source of confusing bugs at worst?

E] Here a handful of plans to take this into account:
1. Make two different versions of the text APIs. One that takes Latin-1 and one that takes UTF-8.
   1. Have the default version be the Latin-1 variant, and suffix the UTF-8 version. This will likely be the least confusing approach for end users.
   2. Do the Win32 thing and have both of them be suffixed, one with _latin1, one with _utf8, and then have an #ifdef at the top that selects which one to use by default. This one makes code maintenance a bit nicer, but ultimately can lead to weird issues.
2. You have to pass the fonts into the functions already. Why not make opening a font take a parameter about whether printing should use UTF-8 or Latin-1? I don't like this idea because, why it maintains backwards compat (mostly), it doesn't make semantic sense. You're carrying additional information in the font struct that's not a font. Moreover, it doesn't let you select dynamically if you're using UTF-8 or Latin-1 for printing at a time.
3. Break backwards compat entirely and add an encoding parameter to all the text functions. I don't like this since the functions are already so long.
4. Fuck it and make people convert encodings from Latin-1 to UTF-8 themselves. Would probably piss off some people.

I'm most partial to 1.i. and 4., but none of them are ideal solutions in any respect. However, I consider all of them superior to using fallbacks.

**Comment by TheOfficialFloW** [comment]
Oddly enough the trademark symbol in param.sfo is encoded in UTF-8, not Latin-1, so it should actually be printed correctly even with UTF-32 conversion. I am for a vita2d_pgf_set_encoding solution, with Latin-1 as default, with that backward compatiblity is supported.

**Comment by endrift** [comment]
This is just a nitpick, but for what it's worth, this isn't UTF-32, and what you were doing wasn't UCS-2. These are both converting from UTF-8 to a single raw codepoint, which has no transformation format (UTF stands for Unicode Transformation Format--a way of encoding codepoints in something that isn't raw codepoints), and passing that directly in. You were just truncating it to BMP codepoints, whereas I was using the full range.

I'll take a look at what I'm doing, as I think I have a PS Plus copy of Golden Abyss I can poke at.

**Pull request merged**
