### PR TITLE
WIP render to texture

### PR DESCRIPTION
**Pull request by ghost**
This is almost working, although vita2d_draw_texture doesn't actually draw the resulting texture to the screen. I'm submitting this now to see if anyone has any ideas on what I'm missing to get this functionality working, as I'm pretty stumped at this point.

### CODE REVIEW

**Comment by xerpi** [comment]
Thanks, gonna try to get that working and merge it asap.

**Comment by frangarcj** [comment]
Got render to texture working on https://github.com/frangarcj/vita2dlib/commit/445291d3881be96fa5b5b1dbbd3d89971be54bb3

I need to find a way to sinchronize rendering to multiple targets (wait for previous rendering)

render to texture1, render texture1 on texture2, ..., render texturen to main render context

It's work with sceGxmFinish (vita2d_wait_rendering_done) but it's no good performance

**Comment by frangarcj** [comment]
Updated with one working 

https://github.com/frangarcj/vita2dlib/commit/09c7f03a447c45fd55c6dd0198e8eddbb36fa029

I will clean up this a bit

**Comment by xerpi** [comment]
Closed with https://github.com/xerpi/libvita2d/pull/48

**Pull request closed without merging**
